---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run playbook
      condition: 1 == 1
      action:
        run_job_template:
          name: 'Integration template'
          organization: 'Default'
          filter: '*'
